using System;
using System.Collections.Generic;
using Vintagestory.API.Common;
using Vintagestory.API.Config;

// <auto-generated Note="Disabling CodeMaid sorting." />
namespace BearsBranchyHarvest
{
    /// <summary>
    /// Settings data object for Bear's Branchy Harvest.
    /// </summary>
    public class BranchyHarvestSettings
    {
        #region Properties

        public string AllowLeafBlockHarvestComment { get => "If true, allows branchy/non-branchy leaf blocks to drop when harvested with a knife. Default is true."; }
        public bool AllowBranchyDropWithKnife { get; set; } = true;
        public bool AllowLeafyDropWithKnife { get; set; } = true;
        public string AlterStickDropsComment { get => "Should the number of sticks dropped by a leaf block be altered by this mod. Default is true."; }
        public bool AlterStickDrops { get; set; } = true;
        public string BranchyDropsComment { get => "The average number of sticks a branchy leaf block should drop and how much the drops should vary. Default is { avg: 3, var: 1}, which makes branchy blocks drop 2 to 4 sticks each time."; }
        public float BranchyStickAverage { get; set; } = 3f;
        public float BranchyStickVariance { get; set; } = 1f;
        public string LeafyDropsComment { get => "The average number of sticks a non-branchy leaf block should drop and how much the drops should vary. Default is { avg: 1.5, var: 0.5}, which is 1 to 2 sticks."; }
        public float LeafyStickAverage { get; set; } = 1.5f;
        public float LeafyStickVariance { get; set; } = 0.5f;
        //public string AlterSeedDropsComment { get => "Should the number of seeds dropped by a leaf block be altered by this mod, and if so, what should the multiplier be. All tree seed drop chances will be multiplied by this. Default is true and 5."; }
        //public bool AlterSeedDrops { get; set; } = true;
        //public float SeedChanceMultiplier { get; set; } = 5f;
        //public string ShearsBoostComment { get => "Whether or not drop chances should be increased when using shears. Default is true."; }
        //public bool AllowShearsBoostDrops { get; set; } = true;
        //public string ShearsMultiplierComment { get => "What multipliers should be applied to drop chances for shears. These replace the ones above when using shears. Default is 0.75 stick chance and 10 seed chance."; }
        //public float LeafyStickChanceShears { get; set; } = 0.75f;
        //public float SeedChanceMultiplierShears { get; set; } = 10f;
        public string AssetsToPatchListComment { get => "List of assets to apply these modifications to."; }
        public List<AssetLocation> patchableAssetList { get; set; } = [
            "game:blocktypes/plant/leaves/normal.json",
            "game:blocktypes/plant/leaves/branchy.json",
            "game:blocktypes/plant/leaves/bamboo.json",
            "bdtree:blocktypes/plant/leaves/normal.json",
            "bdtree:blocktypes/plant/leaves/branchy.json"
            ];
        #endregion Properties
    }

    /// <summary>
    /// Mod subsystem for handling saving and loading of Bear's Branchy Harvest config settings.
    /// </summary>
    public class BranchyHarvestSettingsLoader : ModSystem
    {
        #region Properties

        public static BranchyHarvestSettings? CurrentSettings { get; private set; }
        public static string SettingsFilename { get => "BearsBranchyHarvest.json"; }

        #endregion Properties

        #region Methods

        /// <summary>
        /// Pre-Start, loads before the rest of the mod to handle loading of settings.
        /// </summary>
        public override void StartPre(ICoreAPI api)
        {
            base.StartPre(api);

            LoadOrCreateSettings(api);
        }

        /// <summary>
        /// Attempts to load the mod config settings from a json file. Creates one if none is found.
        /// </summary>
        private void LoadOrCreateSettings(ICoreAPI api)
        {
            try {
                CurrentSettings = api.LoadModConfig<BranchyHarvestSettings>(SettingsFilename);

                if (CurrentSettings == null) {
                    CurrentSettings = new BranchyHarvestSettings();
                    api.StoreModConfig<BranchyHarvestSettings>(CurrentSettings, SettingsFilename);
                    Mod.Logger.Notification(Lang.Get("bearsbranchyharvest:settings-initialize-file"));
                }
            }
            catch (Exception e) {
                Mod.Logger.Error($"{Lang.Get("bearsbranchyharvest:settings-load-error")} {e.Message}");
                CurrentSettings = new BranchyHarvestSettings();
            }
        }

        #endregion Methods
    }
}