using System;
using System.Collections.Generic;
using Vintagestory.API.Common;
using Vintagestory.API.Config;

// <auto-generated Note="Disabling CodeMaid sorting." />
namespace BearsBranchyHarvest
{
    /// <summary>
    /// Settings data object for Bear's Branchy Harvest.
    /// </summary>
    public class BranchyHarvestSettings
    {
        #region Properties

        public string AllowLeafBlockHarvestComment { get => "If true, allows branchy/non-branchy leaf blocks to drop when harvested with a knife. Default is true."; }
        public bool AllowBranchyDropWithKnife { get => allowBranchyDrops; set => allowBranchyDrops = value; }
        private bool allowBranchyDrops = true;
        public bool AllowLeafyDropWithKnife { get => allowLeafyDrops; set => allowLeafyDrops = value; }
        private bool allowLeafyDrops = true;
        public string AlterStickDropsComment { get => "Should the number of sticks dropped by a leaf block be altered by this mod. Default is true."; }
        public bool AlterStickDrops { get => alterStickDrops; set => alterStickDrops = value; }
        private bool alterStickDrops = true;
        public string AlterSeedDropsComment { get => "Should the number of seeds dropped by a leaf block be altered by this mod. Default is true."; }
        public bool AlterSeedDrops { get => alterSeedDrops; set => alterSeedDrops = value; }
        private bool alterSeedDrops = true;
        public string BranchyDropsComment { get => "The average number of sticks a branchy leaf block should drop and how much the drops should vary. Default is { avg: 3, var: 1}, which makes branchy blocks drop 2 to 4 sticks each time. The base chance for a seed drop from any particular tree will be multiplied by the branchySeedMultiplier value."; }
        public float BranchyStickAverage { get => branchyStickAvg; set => branchyStickAvg = value >= 0 ? value : 0; }
        private float branchyStickAvg = 3f;
        public float BranchyStickVariance { get => branchyStickVar; set => branchyStickVar = value >= 0 ? value : 0; }
        private float branchyStickVar = 1f;
        public float BranchySeedMultiplier { get => branchySeedMultiplier; set => branchySeedMultiplier = value >= 1f ? value : 1f; }
        private float branchySeedMultiplier = 5f;
        public string LeafyDropsComment { get => "The average number of sticks a non-branchy leaf block should drop and how much the drops should vary. Default is { avg: 0.50, var: 0}, which is a 50% chance to drop one stick. The base chance for a seed drop from any particular tree will be multiplied by the leafySeedMultiplier value."; }
        public float LeafyStickAverage { get => leafyStickAvg; set => leafyStickAvg = value >= 0 ? value : 0; }
        private float leafyStickAvg = 0.5f;
        public float LeafyStickVariance { get => leafyStickVar; set => leafyStickVar = value >= 0 ? value : 0; }
        private float leafyStickVar = 0;
        public float LeafySeedMultiplier { get => leafySeedMultiplier; set => leafySeedMultiplier = value >= 1f ? value : 1f; }
        private float leafySeedMultiplier = 2f;
        public string ConnectToFencesComment { get => "If true, branchy leaf blocks will connect to fences like other solid blocks. Useful for making hedges that look cohesive."; }
        public bool ConnectToFences { get => connectToFences; set => connectToFences = value; }
        private bool connectToFences = true;
        public string BlacklistComment { get => "List of block/mod names that these changes should not be applied to. The blacklist will apply to any block/mod with a name that contains the string, it need not be a strict match. Be careful to not make it too broad (putting 'l' or 'v' here will disable the mod because it matches all [l]ea[v]es, for example). Turning on developer options and entering creative mode will show block names in the handbook if you need to find the name of a block."; }
        public List<string> BlockBlacklist { get => blockBlacklist; set => blockBlacklist = value; }
        private List<string> blockBlacklist = [];
        public List<string> ModBlacklist { get => modBlacklist; set => modBlacklist = value; }
        private List<string> modBlacklist = [];

        #endregion Properties
    }

    /// <summary>
    /// Mod subsystem for handling saving and loading of Bear's Branchy Harvest config settings.
    /// </summary>
    public class BranchyHarvestSettingsLoader : ModSystem
    {
        #region Constants

        /// <summary>The string name of the settings file, used to load it.</summary>
        public static string SettingsFilename { get => "BearsBranchyHarvest.json"; }

        #endregion Constants

        #region Properties

        /// <summary>A reference to the current settings object.</summary>
        public BranchyHarvestSettings? CurrentSettings { get; private set; }

        #endregion Properties

        #region Methods

        /// <summary>
        /// Pre-Start, loads before the rest of the mod to handle loading of settings.
        /// </summary>
        public override void StartPre(ICoreAPI api)
        {
            base.StartPre(api);

            LoadOrCreateSettings(api);
        }

        /// <summary>
        /// Attempts to load the mod config settings from a json file. Creates one if none is found.
        /// </summary>
        private void LoadOrCreateSettings(ICoreAPI api)
        {
            try {
                CurrentSettings = api.LoadModConfig<BranchyHarvestSettings>(SettingsFilename);

                if (CurrentSettings == null) {
                    CurrentSettings = new BranchyHarvestSettings();
                    Mod.Logger.Notification(Lang.Get("bearsbranchyharvest:settings-initialize-file"));
                }

                api.StoreModConfig<BranchyHarvestSettings>(CurrentSettings, SettingsFilename);
            }
            catch (Exception e) {
                Mod.Logger.Error($"{Lang.Get("bearsbranchyharvest:settings-load-error")} {e.Message}");
                CurrentSettings = new BranchyHarvestSettings();
            }
        }

        #endregion Methods
    }
}